### ISSUE TITLE
xtables-addons incompatible with latest iptables release

### ISSUE THREAD

**Issue by xogium** [bw-oss/xtables-addons#1]
Hi, first of all I didn't know where to post an issue so I went on github, but do correct me if it's wrong place. It seems that v 2.12 is incompatible with latest iptables release, 1.6.1:

* iptables has so name ending with .12 (i.e: libxtables,so.12)
* xtables-addons produces so name ending in .11 and requiring for example libxtables.so.11
* system is archlinux, up to date as of a day ago
Is it planned to make it compatible with latest iptables ?
Thanks

**Comment by codykrieger** [comment]
Hi @xogium—this is an unofficial mirror/fork of xtables-addons. You'll have to file your ticket upstream: http://xtables-addons.sourceforge.net/
